labex course create-cover -r --bg-color "#ffffff" -a linux-terminal-basics --tag "module 01"
labex course create-cover -r --bg-color "#ffffff" -a file-system-navigation-and-file-operations --tag "module 02"
labex course create-cover -r --bg-color "#ffffff" -a viewing-searching-and-editing-files --tag "module 03"
labex course create-cover -r --bg-color "#ffffff" -a shell-r --bg-color "#ffffff"edirection-and-pipelines --tag "module 04"
labex course create-cover -r --bg-color "#ffffff" -a shell-environment-and-variables --tag "module 05"
labex course create-cover -r --bg-color "#ffffff" -a users-groups-and-permissions --tag "module 06"
labex course create-cover -r --bg-color "#ffffff" -a processes-and-job-control --tag "module 07"
labex course create-cover -r --bg-color "#ffffff" -a system-information-and-r --bg-color "#ffffff"esource-monitoring --tag "module 08"
labex course create-cover -r --bg-color "#ffffff" -a disk-filesystems-and-storage-management --tag "module 09"
labex course create-cover -r --bg-color "#ffffff" -a linux-networking-fundamentals --tag "module 10"
labex course create-cover -r --bg-color "#ffffff" -a remote-access-and-secure-file-transfer --tag "module 11"
labex course create-cover -r --bg-color "#ffffff" -a software-package-management --tag "module 12"
labex course create-cover -r --bg-color "#ffffff" -a service-management-with-systemd --tag "module 13"
labex course create-cover -r --bg-color "#ffffff" -a log-management-and-text-processing --tag "module 14"
labex course create-cover -r --bg-color "#ffffff" -a archiving-and-backup --tag "module 15"
labex course create-cover -r --bg-color "#ffffff" -a shell-scripting-fundamentals --tag "module 16"
labex course create-cover -r --bg-color "#ffffff" -a advanced-shell-scripting-techniques --tag "module 17"
labex course create-cover -r --bg-color "#ffffff" -a text-processing-with-awk-and-sed --tag "module 18"
labex course create-cover -r --bg-color "#ffffff" -a scheduled-tasks-and-r --bg-color "#ffffff"outine-maintenance --tag "module 19"
labex course create-cover -r --bg-color "#ffffff" -a boot-process-and-r --bg-color "#ffffff"ecovery --tag "module 20"
labex course create-cover -r --bg-color "#ffffff" -a basic-system-security --tag "module 21"
labex course create-cover -r --bg-color "#ffffff" -a version-control-with-git --tag "module 22"
labex course create-cover -r --bg-color "#ffffff" -a docker-container-basics --tag "module 23"
labex course create-cover -r --bg-color "#ffffff" -a mysql-database-basics --tag "module 24"
labex course create-cover -r --bg-color "#ffffff" -a nginx-web-server --tag "module 25"
labex course create-cover -r --bg-color "#ffffff" -a apache-web-server --tag "module 26"
labex course create-cover -r --bg-color "#ffffff" -a dns-service-administration --tag "module 27"
labex course create-cover -r --bg-color "#ffffff" -a dhcp-service-administration --tag "module 28"
labex course create-cover -r --bg-color "#ffffff" -a nfs-and-samba-file-sharing --tag "module 29"
labex course create-cover -r --bg-color "#ffffff" -a rpm-and-dnf-package-management --tag "module 30"
labex course create-cover -r --bg-color "#ffffff" -a firewalld-configuration --tag "module 31"
labex course create-cover -r --bg-color "#ffffff" -a selinux-administration --tag "module 32"
labex course create-cover -r --bg-color "#ffffff" -a ansible-automation --tag "module 33"
labex course create-cover -r --bg-color "#ffffff" -a haproxy-load-balancing --tag "module 34"
labex course create-cover -r --bg-color "#ffffff" -a keepalived-high-availability --tag "module 35"
labex course create-cover -r --bg-color "#ffffff" -a prometheus-monitoring --tag "module 36"
labex course create-cover -r --bg-color "#ffffff" -a grafana-data-visualization --tag "module 37"
labex course create-cover -r --bg-color "#ffffff" -a centralized-log-management --tag "module 38"
labex course create-cover -r --bg-color "#ffffff" -a github-actions-cicd --tag "module 39"
labex course create-cover -r --bg-color "#ffffff" -a terraform-infrastructure-as-code --tag "module 40"
labex course create-cover -r --bg-color "#ffffff" -a kubernetes-fundamentals --tag "module 41"
labex course create-cover -r --bg-color "#ffffff" -a kubernetes-cluster-administration --tag "module 42"
labex course create-cover -r --bg-color "#ffffff" -a python-for-operations --tag "module 43"